
import com.dbutil.javaConnect;
import com.repository.RepositoryClass;
import java.awt.GridLayout;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import static org.hsqldb.HsqlDateTime.e;
*/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rpran
 */
public class jpanel6 extends javax.swing.JPanel {

    int i = 0;
    String date;
    int total;
    /**
     * Creates new form jpanel3
     */
    public jpanel6() {
        initComponents();
        CurrentDate();
    }

    public void CurrentDate() {

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    String monthh = null;
                    String dayy = null;
                    int month = cal.get(Calendar.MONTH) + 1;
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    if ((month) < 10) {
                        monthh = "0" + month;
                    } else {
                        monthh = "" + month;
                    }
                    if (day < 10) {
                        dayy = "0" + day;
                    } else {
                        dayy = "" + day;
                    }
                    date_txt5.setText(year + "-" + monthh + "-" + dayy);
                    date = year + "-" + monthh + "-" + dayy;
                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    String houur = null;
                    String minuute = null;
                    String seconnd = null;

                    if (hour < 10) {
                        houur = "0" + hour;
                    } else {
                        houur = "" + hour;
                    }
                    if (minute < 10) {
                        minuute = "0" + minute;
                    } else {
                        minuute = "" + minute;
                    }
                    if (second < 10) {
                        seconnd = "0" + second;
                    } else {
                        seconnd = "" + second;
                    }
                    time_txt5.setText(houur + ":" + minuute + ":" + seconnd);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(login_jframe.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }

        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        time_txt5 = new javax.swing.JLabel();
        date_txt5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextPatientId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TextQty = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TextName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        TextDid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        TextTotalWords = new javax.swing.JTextField();
        TextTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableInvoice = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        LabelError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TextPatientName = new javax.swing.JTextField();
        TextDName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Main = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setLayout(null);

        panel.setLayout(null);

        time_txt5.setBackground(new java.awt.Color(255, 255, 255));
        time_txt5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        time_txt5.setForeground(new java.awt.Color(255, 255, 255));
        time_txt5.setText("Time");
        time_txt5.setRequestFocusEnabled(false);
        panel.add(time_txt5);
        time_txt5.setBounds(900, 0, 80, 20);

        date_txt5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        date_txt5.setForeground(new java.awt.Color(255, 255, 255));
        date_txt5.setText("Date");
        panel.add(date_txt5);
        date_txt5.setBounds(900, 20, 80, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Invoice - ");
        panel.add(jLabel2);
        jLabel2.setBounds(210, 10, 100, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HEALTH CENTRE MANAGEMENT SYSTEM");
        panel.add(jLabel3);
        jLabel3.setBounds(320, 8, 500, 40);

        TextPatientId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextPatientIdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextPatientIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextPatientIdMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextPatientIdMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TextPatientIdMouseReleased(evt);
            }
        });
        TextPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPatientIdActionPerformed(evt);
            }
        });
        panel.add(TextPatientId);
        TextPatientId.setBounds(140, 80, 160, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DID:");
        panel.add(jLabel14);
        jLabel14.setBounds(500, 80, 40, 30);

        TextQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextQtyActionPerformed(evt);
            }
        });
        panel.add(TextQty);
        TextQty.setBounds(550, 160, 51, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity:");
        panel.add(jLabel10);
        jLabel10.setBounds(470, 160, 70, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Doctor Name:");
        panel.add(jLabel11);
        jLabel11.setBounds(440, 120, 110, 34);

        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });
        panel.add(TextName);
        TextName.setBounds(140, 160, 270, 30);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2);
        jButton2.setBounds(650, 160, 90, 30);

        TextDid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDidActionPerformed(evt);
            }
        });
        panel.add(TextDid);
        TextDid.setBounds(550, 80, 140, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name of Item:");
        panel.add(jLabel15);
        jLabel15.setBounds(30, 160, 110, 30);

        jButton6.setText("Calculate");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel.add(jButton6);
        jButton6.setBounds(290, 470, 100, 40);

        jButton7.setText("Generate Bill");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel.add(jButton7);
        jButton7.setBounds(620, 470, 140, 40);

        TextTotalWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTotalWordsActionPerformed(evt);
            }
        });
        panel.add(TextTotalWords);
        TextTotalWords.setBounds(150, 530, 600, 40);
        panel.add(TextTotal);
        TextTotal.setBounds(150, 470, 117, 40);

        jLabel17.setText("AMOUNT IN WORDS");
        panel.add(jLabel17);
        jLabel17.setBounds(160, 580, 150, 48);

        TableInvoice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "NAME OF ITEM", "QTY", "UNIT PRICE", "TOTAL PRICE"
            }
        ));
        TableInvoice.setGridColor(new java.awt.Color(102, 255, 0));
        jScrollPane2.setViewportView(TableInvoice);

        panel.add(jScrollPane2);
        jScrollPane2.setBounds(50, 210, 710, 240);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Grand Total:");
        panel.add(jLabel18);
        jLabel18.setBounds(40, 470, 100, 40);

        LabelError.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LabelError.setForeground(new java.awt.Color(255, 0, 0));
        LabelError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelErrorMouseClicked(evt);
            }
        });
        panel.add(LabelError);
        LabelError.setBounds(150, 190, 260, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("In Words:");
        panel.add(jLabel1);
        jLabel1.setBounds(40, 530, 90, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Patient Id:");
        panel.add(jLabel12);
        jLabel12.setBounds(30, 80, 110, 34);
        panel.add(TextPatientName);
        TextPatientName.setBounds(140, 120, 270, 30);
        panel.add(TextDName);
        TextDName.setBounds(550, 120, 190, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Patient Name:");
        panel.add(jLabel13);
        jLabel13.setBounds(30, 120, 110, 34);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backbutton2.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel.add(jButton4);
        jButton4.setBounds(20, 10, 80, 27);

        Main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InvoiceBackground.jpg"))); // NOI18N
        panel.add(Main);
        Main.setBounds(0, 0, 980, 600);

        add(panel);
        panel.setBounds(0, 0, 980, 600);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backbutton2.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(20, 10, 80, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void TextQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextQtyActionPerformed

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) TableInvoice.getModel();
        RepositoryClass Rc = new RepositoryClass();
        String DName;
        int check;
        int Quantity;
       
       
        ResultSet Rs = Rc.checkDrug(TextName.getText());
        try {
            if (!Rs.next()) {
                LabelError.setText("Not In Stock");

            } else {
                //LabelError.setText("");

                DName = TextName.getText();
                Quantity = Integer.parseInt(TextQty.getText());
                check = Rc.retStock(DName);
                if (check < Quantity) {
                    LabelError.setText(DName + " Available Only: " + check);
                   
                } else {
                    i = i + 1;
                    model.addRow(new Object[]{i, TextName.getText(), Integer.parseInt(TextQty.getText())});
                    LabelError.setText("");
                }

            }

        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, e);

        }
        // TextName.setText(null);
        // TextQty.setText(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableInvoice.getModel();
        RepositoryClass Rc = new RepositoryClass();
      

        int j = 1;
        int sum = 0;

        for (int i = 0; i < model.getRowCount(); i++) {

            ResultSet Rs = Rc.InBillDrug(j, (String) model.getValueAt(i, 1), (int) model.getValueAt(i, 2));
            j = j + 1;
            try {

                int add1 = Integer.parseInt(Rs.getString("Cost"));
                model.setValueAt(add1, i, 3);
                model.setValueAt(add1 * (int) model.getValueAt(i,2), i, 4);
                sum = sum + (int) model.getValueAt(i,4);

            } catch (SQLException ex) {
                Logger.getLogger(jpanel6.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
       
        TextTotal.setText("Rs." + Integer.toString(sum));
        NumberToWord obj = new NumberToWord();
        total = sum;
        String S = obj.convertNumberToWords(sum);
        TextTotalWords.setText("Rs." + S);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TextTotalWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTotalWordsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TextTotalWordsActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        RepositoryClass Rc = new RepositoryClass();
        Rc.DeleteBill();
        String DName;
        int Quantity;
        int Sn = 1;
        DefaultTableModel model = (DefaultTableModel) TableInvoice.getModel();
        ResultSet rs = Rc.InBillStore(total);
         int BillId = 0;
        
         try{   
             if(rs.next())
             {
                BillId = Integer.parseInt(rs.getString("BillId"));
             }
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
        for (int i = 0; i < model.getRowCount(); i++) {
            DName = model.getValueAt(i, 1).toString();
            Quantity = Integer.parseInt(model.getValueAt(i, 2).toString());
            Rc.decStock(DName, Quantity);
            Rc.InBillDrug(Sn, DName, Quantity);
            Rc.drugPatient(TextPatientId.getText(),DName,Quantity,date,BillId);
            Sn = Sn+1;
          
        }
       
        String D = TextDid.getText();
        
        Map parameters = new HashMap();
        parameters.put("Total", TextTotal.getText());
        
        parameters.put("TotalWords", TextTotalWords.getText());
        parameters.put("PatientName", TextPatientName.getText());
         parameters.put("DoctorName", TextDName.getText());
        try {
            //String report = "C:\\ProgrammingJava\\StandardFormatExample\\MainReport.jrxml";

/*            JasperDesign jd = JRXmlLoader.load("C:\\ProgrammingJava\\StandardFormatExample\\Bill.jrxml");
            String sql = "select distinct SN,DrugName,Cost,No,TotalCost from bill ";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameters, javaConnect.ConnecrDb());
            JasperViewer.viewReport(jp, false);
*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void TextDidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDidActionPerformed
        // TODO add your handling code here:
         RepositoryClass Rc = new RepositoryClass();
        ResultSet Rs = Rc.viewDoctor(Integer.parseInt(TextDid.getText()));
         try{
            if(Rs.next())
            {
                String add1 = Rs.getString("DoctorName");
                TextDName.setText(add1);
            }
            else
            {
                LabelError.setText("Sorry Doctor Not Found");
            }
        }
        catch(Exception e){
        }
        
    }//GEN-LAST:event_TextDidActionPerformed

    private void LabelErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelErrorMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_LabelErrorMouseClicked

    private void TextPatientIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextPatientIdMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextPatientIdMouseExited

    private void TextPatientIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextPatientIdMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TextPatientIdMouseClicked

    private void TextPatientIdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextPatientIdMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TextPatientIdMouseReleased

    private void TextPatientIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextPatientIdMouseEntered
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TextPatientIdMouseEntered

    private void TextPatientIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextPatientIdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPatientIdMousePressed

    private void TextPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPatientIdActionPerformed
        // TODO add your handling code here:
        RepositoryClass Rc = new RepositoryClass();
        ResultSet Rs = Rc.viewOutPatient(TextPatientId.getText());
        try{
            if(Rs.next())
            {
                String add1 = Rs.getString("Name");
                TextPatientName.setText(add1);
            }
            else
            {
                LabelError.setText("Sorry Patient Not Found");
            }
        }
        catch(Exception e){
        }
        
    }//GEN-LAST:event_TextPatientIdActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        panel.removeAll();
        panel.setLayout(new GridLayout(1, 2));
        panel.add(new jpanel1());
        panel.updateUI();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        panel.removeAll();
        panel.setLayout(new GridLayout(1, 2));
        panel.add(new jpanel1());
        panel.updateUI();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelError;
    private javax.swing.JLabel Main;
    private javax.swing.JTable TableInvoice;
    private javax.swing.JTextField TextDName;
    private javax.swing.JTextField TextDid;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField TextPatientId;
    private javax.swing.JTextField TextPatientName;
    private javax.swing.JTextField TextQty;
    private javax.swing.JTextField TextTotal;
    private javax.swing.JTextField TextTotalWords;
    private javax.swing.JLabel date_txt5;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel time_txt5;
    // End of variables declaration//GEN-END:variables
}
